--use DbYeni
--CREATE TABLE TBLMUSTERI
--(
--ID INT PRIMARY KEY IDENTITY(1,1),
--AD VARCHAR(20),
--SOYAD VARCHAR(20),
--SEHIR VARCHAR(15),
--BAKIYE DECIMAL(18,2)
--)

--CREATE TABLE TBLKATEGORI
--(
--KATEGORIID INT PRIMARY KEY IDENTITY(1,1),
--AD VARCHAR(20)
--)

--CREATE TABLE TBLURUN
--(
--URUNID INT PRIMARY KEY IDENTITY(1,1),
--AD VARCHAR(20),
--ALISFIYAT DECIMAL(18,2),
--SATISFIYAT DECIMAL(18,2),
--STOK SMALLINT,
--DURUM BIT,
--KATEGORI INT
--)

--CREATE TABLE TBLSATIS
--(
--SATISID INT PRIMARY KEY IDENTITY(1,1),
--MUSTERI INT,
--URUN INT,
--TARIH DATE
--)

--UPDATE TBLSTOK SET TOPLAMURUN = (SELECT COUNT(*) FROM TBLURUN)

--CREATE TRIGGER ARTTIR
--ON TBLURUN
--AFTER INSERT
--AS
--UPDATE TBLSTOK SET TOPLAMURUN+=1

--UPDATE TBLSTOK SET TOPLAMURUN =(SELECT SUM(STOK) FROM TBLURUN)
--DROP TRIGGER ARTTIR

--CREATE TRIGGER ARTTIR
--ON TBLURUN
--AFTER INSERT
--AS
--DECLARE @STOKSAYI INT
--SELECT @STOKSAYI= STOK FROM INSERTED
--UPDATE TBLSTOK SET TOPLAMURUN+=@STOKSAYI

--CREATE TRIGGER AZALT
--ON TBLURUN
--AFTER DELETE
--AS
--DECLARE @STOKSAYI INT
--SELECT @STOKSAYI = STOK FROM DELETED
--UPDATE TBLSTOK SET TOPLAMURUN=TOPLAMURUN-@STOKSAYI

--INSERT INTO TBLURUN(AD,STOK) VALUES ('MIXER',80)

--BEGIN TRANSACTION
--INSERT INTO TBLKATEGORI (AD) VALUES ('TV')
--INSERT INTO TBLKATEGORI (AD) VALUES ('HALI')
--SELECT * FROM TBLKATEGORI
--ROLLBACK

--BEGIN TRANSACTION
--INSERT INTO TBLURUN (AD,STOK) VALUES ('ÜRÜN3',10)
--INSERT INTO TBLURUN (AD,STOK) VALUES ('ÜRÜN4','B')
--SELECT * FROM TBLURUN
--COMMIT

--CREATE FUNCTION STOKARTTIR(@ADET INT)
--RETURNS INT
--AS
--BEGIN
--RETURN @ADET + 26
--END

--SELECT AD,STOK,DBO.STOKARTTIR(STOK) AS 'NEW' FROM TBLURUN

--CREATE FUNCTION ODEV(@ADET INT)
--RETURNS INT
--AS
--BEGIN
--RETURN SQRT(@ADET) * 3
--END

--SELECT AD,STOK,DBO.ODEV(STOK) AS 'NEW' FROM TBLURUN

--ALTER FUNCTION KUCUKHARF(@ISIM VARCHAR(20))
--RETURNS VARCHAR(20)
--AS
--BEGIN
--RETURN LOWER(@ISIM)
--END

--SELECT DBO.KUCUKHARF(AD),STOK FROM TBLURUN

--CREATE FUNCTION KDV(@FIYAT DECIMAL(18,2))
--RETURNS DECIMAL(18,2)
--AS
--BEGIN
--RETURN @FIYAT * 1.18
--END

--SELECT AD,SATISFIYAT,DBO.KDV(SATISFIYAT) FROM TBLURUN

--CREATE FUNCTION URUNBILGI(@URID INT)
--RETURNS TABLE
--AS
--RETURN SELECT * FROM TBLURUN WHERE URUNID = @URID

--SELECT * FROM DBO.URUNBILGI(4)

--CREATE FUNCTION STOKAZ(@STOK INT)
--RETURNS TABLE
--AS
--RETURN SELECT * FROM TBLURUN WHERE STOK < @STOK

--SELECT * FROM DBO.STOKAZ(30)

--CREATE TABLE TABLO1
--(
--ID INT IDENTITY (1,1),
--AD VARCHAR(20)
--)
--DECLARE @SAYAC INT = 1
--WHILE @SAYAC < 250001
--BEGIN
--INSERT TABLO1
--SELECT 'KÝTAP' + CAST(@SAYAC AS VARCHAR(20))
--SET @SAYAC = @SAYAC + 1
--END

--SELECT COUNT(*) FROM TABLO1

--SELECT * FROM TABLO1 WHERE ID = 210387
--SET STATISTICS IO ON
--SET STATISTICS TIME ON
--SELECT * FROM TABLO1 WHERE ID = 210387

--CREATE CLUSTERED INDEX TABLOKAYITGETIR
--ON TABLO1(ID)
--SELECT * FROM TABLO1 WHERE ID =210387



