--Select * From Tablo_Ogrenciler Where OGRSEHIR = 'Adana' or OGRKULUP = 'Satranç'

--Select * From TBLNOTLAR 
--Select (SINAV1+SINAV2+SINAV3)/3 From TBLNOTLAR

--Insert Into Tablo_Ogrenciler (OGRAD,OGRSOYAD,OGRSEHIR) Values ('Baran','Yücedað','Elazýð')
--Select * From Tablo_Ogrenciler

--Insert Into TBLNOTLAR (OGRENCI,DERS,SINAV1,SINAV3) Values (6,2,88,67)

--Delete From TBLDERSLER Where DERSID = 6

--Truncate Table TBLDERSLER

--Update Tablo_Ogrenciler Set OGRCINSIYET = 'Kýz' Where OGRID = 4 or OGRID = 5

--Update Tablo_Ogrenciler set OGRKULUP = 'Kitaplýk' Where OGRAD='Baran'

--Insert Into TBLNOTLAR (OGRENCI,DERS,SINAV1,SINAV2) VALUES(5,2,78,66)

--Update TBLNOTLAR set ORTALAMA = (SINAV1+SINAV2+SINAV3)/3
--Update TBLNOTLAR set durum=0 Where ortalama<50

--SElect Count (*) As 'Toplam Kayýt' From Tablo_Ogrenciler
--Select Count (*) As 'Toplam Kiþi' From Tablo_Ogrenciler Where OGRSEHIR = 'Adana'

--Select Sum(Sýnav1),Sum (Sýnav2),Sum (Sýnav3) From TBLNOTLAR
--Select Avg(Sýnav1),Avg(Sýnav2),Avg(Sýnav3) FRom TBLNOTLAR
--Select Max(Sýnav1),Max(Sýnav2),Max(Sýnav3) From TBLNOTLAR
--Select min(Sýnav1),min(Sýnav2),min(Sýnav3) From TBLNOTLAR

--Select OGRSEHIR,Count (*) as 'Toplam' From Tablo_Ogrenciler GROUP BY OGRSEHIR

--Select OGRCINSIYET , COUNT (*) AS 'TOPLAM' FROM Tablo_Ogrenciler GROUP BY OGRCINSIYET
--Select DURUM, COUNT(*) AS 'Geçme Kalma' FROM TBLNOTLAR GROUP BY DURUM

--Select OGRKULUP,Count(*) FRom Tablo_Ogrenciler GRoup By OGRKULUP
--SElect max (OGRKULUP) from Tablo_Ogrenciler

--Select OGRSEHIR , cOUNT(*) AS 'SAYI' FROM Tablo_Ogrenciler GROUP BY OGRSEHIR HAVING COUNT(*) =2
--Select OGRKULUP , COUNT(*) from Tablo_Ogrenciler group by OGRKULUP HAVING OGRKULUP = 'Kitaplýk'
--Select ORTALAMA,COUNT(*) AS 'GEÇENLER' FROM TBLNOTLAR group by ORTALAMA HAVING ORTALAMA >= 50 
--Select ORTALAMA,COUNT(*) AS 'KALANLAR' FROM TBLNOTLAR group by ORTALAMA HAVING ORTALAMA < 50 

--Select * From Tablo_Ogrenciler Where OGRAD = 'Ali' --Where içinde ali olanlarý seçiyor
--Select * From Tablo_Ogrenciler Where OGRAD Like '%a%' or OGRSOYAD like '%a%'
--SElect * from Tablo_Ogrenciler Where OGRAD LIKE 'a%' and OGRCINSIYET = 'erkek'
--SElect * from Tablo_Ogrenciler Where OGRSEHIR LIKE '%mir%' 
--Select * FRom Tablo_Ogrenciler Where OGRKULUP not like '%a%'
--Select * FRom Tablo_Ogrenciler Where OGRKULUP not like 's%'

--Select  distinct OGRSEHIR FROM Tablo_Ogrenciler
--Select Count(distinct(OGRSEHIR)) FROM Tablo_Ogrenciler
--Select Distinct OGRKULUP FROM Tablo_Ogrenciler
--sELECT COUNT(DISTINCT(OGRKULUP)) AS 'KULÜP SAYISI' FROM Tablo_Ogrenciler

--Select * FRom Tablo_Ogrenciler order by OGRSEHIR
--SELECT DISTINCT OGRKULUP FROM Tablo_Ogrenciler ORDER BY OGRKULUP DESC
--SELECT TOP 60 PERCENT * FROM Tablo_Ogrenciler
--SELECT * FROM Tablo_Ogrenciler WHERE OGRSEHIR LIKE '%ir_%'
--select * FROM Tablo_Ogrenciler WHERE OGRAD LIKE '%[N,I]'
--Select * From Tablo_Ogrenciler Where OGRKULUP like '%[a-h]'

--Select top 4 * From Tablo_Ogrenciler order by OGRID desc
--Select top 60 percent * from Tablo_Ogrenciler

--Select * From Tablo_Ogrenciler Where OGRSEHIR = 'Ýzmir' or OGRSEHIR = 'Ankara' 
--Select * From Tablo_Ogrenciler Where OGRSEHIR in('Ýzmir','Ankara','Edirne')
--Select * From TBLNOTLAR Where SINAV1 in (70,75,80,85,90)
--Select * From TBLNOTLAR Where SINAV1 not in (70,75,80,85,90)

--Select * From TBLNOTLAR Where ORTALAMA BETWEEN 74 AND 100
--Select * From Tablo_Ogrenciler Where OGRAD  NOT BETWEEN 'A' AND 'N'

--Update Tablo_Ogrenciler Set OGRKULUP = 4 Where OGRKULUP = 'Gezi'

--insert into Tablo_Ogrenciler (OGRAD,OGRKULUP,OGRSEHIR) VALUES ('Berna',4,'Ankara')

--Select NOTID,OGRAD + ' ' +OGRSOYAD AS 'AD SOYAD',DERSAD,SINAV1,SINAV2,SINAV3,ORTALAMA,DURUM FRom TBLNOTLAR
--INNER JOIN TBLDERSLER
--ON TBLNOTLAR.DERS = TBLDERSLER.DERSID
--INNER JOIN Tablo_Ogrenciler
--ON TBLNOTLAR.OGRENCI = Tablo_Ogrenciler.OGRID

--SELECT * FROM TBLNOTLAR

--UPDATE TBLNOTLAR SET ORTALAMA = (SINAV1+SINAV2+SINAV3)/3 WHERE DERS = 1 
--Update TBLNOTLAR set durum=1 Where ortalama>=50

--Dersler tablosunda ismi matematik olan derse ait sýnav not bilgisi
--SUBQUERY (ALT SORGU)

--Select * from TBLNOTLAR Where DERS=(SELECT DERSID FROM TBLDERSLER Where DERSAD='Matematik')
--Select * FROM TBLNOTLAR where SINAV1 = (Select max (SINAV1) From TBLNOTLAR where DERS = 1)

--insert into Tablo_Ogrenciler (OGRAD,OGRSOYAD,OGRCINSIYET,OGRKULUP,OGRSEHIR) VALUES ('Mehmet','Yücedað','Erkek',2,'Adana')

--Select * FROM TBLNOTLAR
--INNER JOIN Tablo_Ogrenciler
--ON Tablo_Ogrenciler.OGRID = TBLNOTLAR.OGRENCI

--Select * FROM TBLNOTLAR
--Right JOIN Tablo_Ogrenciler
--ON Tablo_Ogrenciler.OGRID = TBLNOTLAR.OGRENCI

--Select * FROM TBLNOTLAR
--Full JOIN Tablo_Ogrenciler
--ON Tablo_Ogrenciler.OGRID = TBLNOTLAR.OGRENCI

--Select * FRom TBLKULUPLER union Select * FRom TBLDERSLER

--Select 20 + 4 As 'Toplam' , 20 - 4 As 'Fark' , 20 * 4 As 'Çarpým' , 20 / 4 As 'Bölüm'

--Select * FRom TBLNOTLAR Where DERS = 1
--Update TBLNOTLAR Set SINAV2 = SINAV2+10 From TBLNOTLAR Where DERS = 1
--Update TBLNOTLAR set SINAV2=100 Where SINAV2>100
--Select Avg(ORTALAMA) From TBLNOTLAR Where DERS = 1

--SINIF ORTALAMALAMASININ ALTINDA OLAN ÖÐRENCÝLERÝN 'DURUM2 'SÜTUNLARININ 
--YANINA 'ALTINDA' AKSÝ DURUMDA 'ÜSTÜNDE' YAZDIRAN SORGU?

--SELECT *,'ÜSTÜNDE' AS 'DURUM2' FROM TBLNOTLAR
--WHERE ORTALAMA>=(SELECT AVG(ORTALAMA) FROM TBLNOTLAR)
--UNION
--SELECT *,'ALTINDA' AS 'DURUM2' FROM TBLNOTLAR
--WHERE ORTALAMA<(SELECT AVG(ORTALAMA) FROM TBLNOTLAR)

--Select * From TBLNOTLAR
--Select ABS(-85) AS 'Mutlak'
--Select power(2,4) as 'Üs'

--Select power(SINAV1,2) FRom TBLNOTLAR
--SElect sqrt(711) as 'Karakök'

--Select floor(4.86) AS 'Taban'
--SElect ceiling(4.86) as 'Tavan'

--Select sum(SINAV1) fROM TBLNOTLAR WHERE OGRENCI = 1
--SELECT DERS,SINAV1 FROM TBLNOTLAR WHERE OGRENCI = 1

--SELECT DERSAD,SINAV1,SINAV2,SINAV3 FROM TBLNOTLAR 
--INNER JOIN TBLDERSLER 
--ON TBLNOTLAR.DERS=TBLDERSLER.DERSID 
--WHERE OGRENCI = (SELECT OGRID from Tablo_Ogrenciler where ograd = 'Ayþe' and ogrsoyad = 'Çýnar' )

--Select OGRAD + '  '+ OGRSOYAD AS 'ADSOYAD' ,DERSAD,SINAV1,'ÜSTÜNDE' as 'DURUM' from TBLNOTLAR
--INNER JOIN Tablo_Ogrenciler
--ON TBLNOTLAR.OGRENCI=Tablo_Ogrenciler.OGRID
--INNER JOIN TBLDERSLER
--ON TBLNOTLAR.DERS=TBLDERSLER.DERSID
--WHERE  OGRENCI = (SELECT OGRID from Tablo_Ogrenciler where OGRAD='Ayþe' and OGRSOYAD = 'Çýnar') and SINAV1>= (Select AVG(ORTALAMA) from TBLNOTLAR) and DERS=(Select DERSID from TBLDERSLER where DERSAD='Algoritma')

--Union

--Select OGRAD + '  '+ OGRSOYAD AS 'ADSOYAD' ,DERSAD,SINAV1,'ALTINDA' as 'DURUM' from TBLNOTLAR
--INNER JOIN Tablo_Ogrenciler
--ON TBLNOTLAR.OGRENCI=Tablo_Ogrenciler.OGRID
--INNER JOIN TBLDERSLER
--ON TBLNOTLAR.DERS=TBLDERSLER.DERSID
--WHERE  OGRENCI = (SELECT OGRID from Tablo_Ogrenciler where OGRAD='Ayþe' and OGRSOYAD = 'Çýnar') and SINAV1<(Select AVG(ORTALAMA) from TBLNOTLAR) and DERS=(Select DERSID from TBLDERSLER where DERSAD='Algoritma')

--SELECT UPPER ('merhaba') as 'Sütun'
--SELECT UPPER(OGRAD) AS 'Öðrenci Adý' , upper(OGRSOYAD) as 'Öðrenci Soyadý',
--lower(OGRSEHIR) AS 'Þehir'
--FROM Tablo_Ogrenciler
--Select upper(OGRAD) AS 'Adý',lower(OGRSOYAD) AS 'Soyadý',OGRSEHIR AS 'Þehir' from Tablo_Ogrenciler 
--where OGRSEHIR = 'Adana' and OGRKULUP=(Select KULUPID FROM TBLKULUPLER WHERE KULUPID=2)

--Select UPPER(OGRAD)+ ' ' + LOWER(OGRSOYAD) as 'Ad ve Soyad', OGRSEHIR as 'Þehir' from Tablo_Ogrenciler
--inner join TBLKULUPLER
--on TBLKULUPLER.KULUPID=Tablo_Ogrenciler.OGRKULUP
--where
--OGRSEHIR='Adana' AND KULUPAD= 'Kitaplýk'

--Select SUBSTRING(OGRAD,1,1)+ '.' + OGRSOYAD as 'Ad-Soyad',substring(KULUPAD,1,3) as 'Kulüp' FROM Tablo_Ogrenciler
--inner join TBLKULUPLER
--on Tablo_Ogrenciler.OGRKULUP=TBLKULUPLER.KULUPID

--Select left('Merhaba Dünya',4), right('MErhaba istanbul',2)
--select left(ograd,1) + '.' + ogrsoyad as 'Ad-Soyad' from Tablo_Ogrenciler

--Select LEFT(DERSAD,3),avg(ortalama) from TBLNOTLAR
--inner join tbldersler
--on TBLDERSLER.DERSID=TBLNOTLAR.DERS
--GROUP BY DERSAD

--Select LEN('Merhaba')
--Select OGRAD,LEN(OGRAD),OGRKULUP FROM Tablo_Ogrenciler WHERE OGRSEHIR='Adana' AND
--OGRKULUP=(SELECT KULUPID FROM TBLKULUPLER WHERE KULUPAD='Kitaplýk')
--SELECT * FROM Tablo_Ogrenciler WHERE LEN(OGRAD) = 4 OR LEN(OGRAD) = 3
--SELECT * FROM Tablo_Ogrenciler WHERE LEN(OGRAD+OGRSOYAD) <=7

--SELECT ltrim('                Korkma Sönmez Bu Þafaklarda Yüzen Al Sancak'             )
--select REPLACE('Murat Yücedað','Yücedað','Y.dað')
--SELECT REPLACE(REPLACE('MERHABA HAVA BUGÜN SOÐUK','A','E'),'H','Z')

--Select CHARINDEX('E','SQL DERSLERÝNE DEVAM EDÝYORUZ',20)
--SELECT LEN('SQL DERSLERÝNE DEVAM EDÝYORUZ')
--SELECT CHARINDEX('A',OGRAD) FROM Tablo_Ogrenciler
--SELECT REVERSE('mURAT')
--SELECT REVERSE(DERSAD) FROM TBLDERSLER

--create database SatisDB
--use SatisDB
--Create Table TBLKATEGORI
--(
--KATEGORIID tinyint identity(1,1) primary key,
--KATEGORIAD varchar(50)
--)
--CREATE TABLE TBLURUNLER
--(
--URUNID int identity(1,1) primary key,
--URUNAD varchar(50),
--URUNMARKA VARCHAR(50),
--KATEGORI TINYINT,
--URUNALISFIYAT DECIMAL(18,2),
--URUNSATISFIYAT DECIMAL(18,2),
--URUNSTOK SMALLINT CHECK(URUNSTOK>0),
--URUNDURUM BIT DEFAULT '1'
--)

--CREATE TABLE TBLPERSONEL
--(
--PERSONELID SMALLINT IDENTITY PRIMARY KEY,
--PERSONELADSOYAD VARCHAR(50)
--)
--CREATE TABLE TBLMUSTERI
--(
--MUSTERIID INT PRIMARY KEY IDENTITY(1,1),
--MUSTERIAD VARCHAR(50),
--MUSTERISOYAD VARCHAR(50),
--MUSTERISEHIR VARCHAR(13),
--MUSTERIBAKIYE DECIMAL(18,2)
--)
--CREATE TABLE TBLHAREKET
--(
--HAREKETID INT PRIMARY KEY IDENTITY(1,1),
--URUN INT,
--MUSTERI INT,
--PERSONEL SMALLINT,
--ADET INT,
--TUTAR DECIMAL(18,2),
--TARIH SMALLDATETIME
--)
--TRUNCATE TABLE TBLURUNLER

--INSERT INTO TBLKATEGORI(KATEGORIAD) VALUES ('BÝLGÝSAYAR')
--INSERT INTO TBLKATEGORI(KATEGORIAD) VALUES ('BEYAZ EÞYA')
--INSERT INTO TBLKATEGORI(KATEGORIAD) VALUES ('KÜÇÜK EV ALETÝ')
--INSERT INTO TBLKATEGORI(KATEGORIAD) VALUES ('TV')

--INSERT INTO TBLURUNLER(URUNAD,URUNMARKA,KATEGORI,URUNALISFIYAT,URUNSATISFIYAT,URUNSTOK)
--VALUES ('BUZDOLABI','SIEMENS',2,4356,4588,10)
--SELECT * FROM TBLURUNLER

--UPDATE TBLURUNLER SET URUNAD = 'SU ISITICI' WHERE URUNAD ='KETTLE'
--SELECT KATEGORIAD,COUNT(*) AS 'TOPLAM URUN' FROM TBLURUNLER
--INNER JOIN TBLKATEGORI
--ON TBLURUNLER.KATEGORI=TBLKATEGORI.KATEGORIID
--GROUP BY KATEGORIAD ORDER BY COUNT(*)

--KATEGORÝ ADI BÝLGÝSAYAR OLAN ÜRÜNLERÝN SATIÞ FIYATINA 500 TL ZAM YAPALIM

--UPDATE TBLURUNLER SET URUNSATISFIYAT+=500 WHERE KATEGORI=
--(SELECT KATEGORIID FROM TBLKATEGORI WHERE KATEGORIAD='BÝLGÝSAYAR')

-- TV KATEGORÝSÝNDEKÝ ÜRÜNLERÝN FÝYATINA %10 ÝNDÝRÝM...

--UPDATE TBLURUNLER SET URUNSATISFIYAT = URUNSATISFIYAT - URUNSATISFIYAT/10 WHERE KATEGORI=
--(SELECT KATEGORIID FROM TBLKATEGORI WHERE KATEGORIAD='TV')

--SELECT COUNT(*) AS 'KAÇ FARKLI URUN',SUM(URUNSTOK) AS 'STOK SAYISI' FROM TBLURUNLER
--SELECT * FROM TBLURUNLER

--SELECT URUNID,URUNAD,URUNMARKA,KATEGORIAD,URUNSATISFIYAT,URUNALISFIYAT,URUNSTOK,
--(URUNSATISFIYAT-URUNALISFIYAT) AS 'KAR',
--(URUNSATISFIYAT-URUNALISFIYAT)*URUNSTOK AS 'TOPLAM KAR'
--FROM TBLURUNLER INNER JOIN TBLKATEGORI
--ON TBLURUNLER.KATEGORI=TBLKATEGORI.KATEGORIID

--update TBLURUNLER
--set URUNSATISFIYAT=URUNSATISFIYAT+URUNSATISFIYAT*0.20
--where (URUNSATISFIYAT-URUNSATISFIYAT)*URUNSTOK<1000

--AS in ALTINDA KALAN PROSEDÜRÜMÜ OLUÞTURUYOR
--CREATE PROCEDURE HAREKETLER
--AS
--SELECT HAREKETID,URUNAD,MUSTERIAD + ' ' + MUSTERISOYAD AS 'AD-SOYAD',
--PERSONELADSOYAD AS 'PERSONEL AD-SOYAD',ADET,TUTAR,TARIH
--FROM TBLHAREKET INNER JOIN TBLURUNLER
--ON TBLHAREKET.URUN=TBLURUNLER.URUNID
--INNER JOIN TBLMUSTERI
--ON TBLHAREKET.MUSTERI=TBLMUSTERI.MUSTERIID
--INNER JOIN TBLPERSONEL
--ON TBLHAREKET.PERSONEL=TBLPERSONEL.PERSONELID

--EXECUTE HAREKETLER

--cREATE PROCEDURE DENEME
--AS
--SELECT * FROM TBLURUNLER WHERE URUNSTOK>10

--EXEC DENEME

--DROP PROCEDURE DENEME

--ALTER PROCEDURE [dbo].[HAREKETLER]
--AS
--SELECT HAREKETID,URUNAD,LEFT(MUSTERIAD,1) + '.' + MUSTERISOYAD AS 'AD-SOYAD',
--PERSONELADSOYAD AS 'PERSONEL AD-SOYAD',ADET,TUTAR,TARIH
--FROM TBLHAREKET INNER JOIN TBLURUNLER
--ON TBLHAREKET.URUN=TBLURUNLER.URUNID
--INNER JOIN TBLMUSTERI
--ON TBLHAREKET.MUSTERI=TBLMUSTERI.MUSTERIID
--INNER JOIN TBLPERSONEL
--ON TBLHAREKET.PERSONEL=TBLPERSONEL.PERSONELID

--EXEC HAREKETLER

--ALTER PROCEDURE URUNGETIR
--@DEGER VARCHAR(50)='BUZDOLABI'
--AS
--SELECT URUNAD,URUNSTOK,URUNMARKA FROM TBLURUNLER
--WHERE URUNAD=@DEGER

--EXEC URUNGETIR @DEGER='LAPTOP'

--ALTER PROCEDURE STOKSAYI
--@DEGER SMALLINT = 0
--AS
--SELECT URUNSTOK,URUNAD FROM TBLURUNLER WHERE URUNSTOK>@DEGER

--EXEC STOKSAYI @DEGER = 9

--SELECT * FROM TBLHAREKET WHERE DATEPART(DAY,TARIH) BETWEEN 1 AND 3 AND MUSTERI=1
--SELECT * FROM TBLHAREKET WHERE DATEPART(DAY,TARIH) BETWEEN 1 AND 3 AND MUSTERI=
--(SELECT MUSTERIID FROM TBLMUSTERI WHERE MUSTERISEHIR='ANKARA')

--SELECT DATENAME(MONTH,GETDATE()),DATENAME(MONTH,'2019.01.15')
--SELECT DATENAME(WEEKDAY,GETDATE())
--SELECT DATENAME(WEEKDAY,'2019.06.10')

--SELECT DATEDIFF(MONTH,'2010.10.25',GETDATE())
--SELECT DATEDIFF(DAY,TARIH,GETDATE()) FROM TBLHAREKET WHERE HAREKETID = 1

--SELECT DATEADD(YEAR,3,'2009.10.25')
--SELECT DATEADD(DAY,45,GETDATE())

--SELECT URUNAD,COUNT(*) FROM TBLHAREKET
--INNER JOIN TBLURUNLER
--ON TBLHAREKET.URUN = TBLURUNLER.URUNID
--GROUP BY URUNAD ORDER BY COUNT(*)

--SELECT * FROM TBLHAREKET WHERE URUN IN(SELECT URUNID FROM TBLURUNLER WHERE KATEGORI=1)
--Select * From TBLHAREKET Where URUN IN
--(Select URUNID From TBLURUNLER Where KATEGORI=
--(Select KATEGORIID From TBLKATEGORI Where KATEGORIAD='Bilgisayar'))

--SELECT * FROM TBLHAREKET WHERE MUSTERI IN
--(SELECT MUSTERIID FROM TBLMUSTERI WHERE MUSTERISEHIR='ADANA')

--SELECT * FROM TBLHAREKET WHERE URUN IN (SELECT URUNID FROM TBLURUNLER WHERE 
--KATEGORI=(SELECT KATEGORIID FROM TBLKATEGORI WHERE KATEGORIAD='BEYAZ EÞYA'))

--SELECT SUM(TUTAR) FROM TBLHAREKET WHERE MUSTERI IN(SELECT MUSTERIID FROM TBLMUSTERI
--WHERE MUSTERISEHIR IN('ADANA','BURSA','ANKARA'))

--SELECT * FROM TBLHAREKET WHERE URUN=1
--UPDATE TBLURUNLER SET URUNSTOK=URUNSTOK-(SELECT SUM(ADET) FROM TBLHAREKET WHERE
--URUN=10) WHERE URUNID=10

--CREATE TABLE KASA 
--(
--TOPLAM DECIMAL(18,2)
--)
--INSERT INTO TBLKASA VALUES(0)
--SELECT * FROM TBLKASA
--UPDATE TBLKASA SET TOPLAM=(SELECT SUM(TUTAR) FROM TBLHAREKET)

--CREATE TABLE TBLSAYAC
--(
--ISLEM INT
--)
--INSERT INTO TBLSAYAC VALUES(0)

--UPDATE TBLSAYAC SET ISLEM=(SELECT COUNT(*) FROM TBLHAREKET)

--CREATE TRIGGER ISLEMARTIS
--ON TBLHAREKET 
--AFTER INSERT
--AS
--UPDATE TBLSAYAC  SET ISLEM=ISLEM+1

--CREATE TABLE TBLTOPLAMKATEGORI
--(
--ADET TINYINT
--)

--UPDATE TBLTOPLAMKATEGORI SET ADET=(SELECT COUNT(*) FROM TBLKATEGORI)

--CREATE TRIGGER KATEGORIARTIS
--ON TBLKATEGORI
--AFTER INSERT
--AS
--UPDATE TBLTOPLAMKATEGORI SET ADET+=1

--CREATE TRIGGER KATEGORIAZALIS
--ON TBLKATEGORI
--AFTER DELETE
--AS
--UPDATE TBLTOPLAMKATEGORI SET ADET-=1

--CREATE VIEW TEST1
--AS
--SELECT * FROM TBLKATEGORI

--SELECT * FROM TEST1
--ALTER VIEW TEST1
--AS
--SELECT * FROM TBLKATEGORI WHERE KATEGORIID<4

--SELECT * FROM TEST1

--SELECT * FROM TEST1

--SELECT * FROM TEST3

